export const ARTICLES_LOADING = 'ARTICLES_LOADING';
export const ADD_ARTICLES = 'ADD_ARTICLES';
export const ARTICLES_FAILED = 'ARTICLES_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

